import { CSSProperties } from 'react';

export const styles: { [key: string]: CSSProperties } = {
  pageContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '0 20px 20px 20px',
    minHeight: 'calc(100vh - 40px)',
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.1)',
    width: '100%',
    boxSizing: 'border-box',
  },
  header: {
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '20px 20px',
    borderBottom: '1px solid #eee',
    marginBottom: '30px',
    boxSizing: 'border-box',
  },
  logoContainer: {
    display: 'flex',
    alignItems: 'center',
    cursor: 'pointer',
  },
  logo: {
    width: '50px',
    height: '50px',
    marginRight: '15px',
  },
  title: {
    fontSize: '2rem',
    color: '#007AFF',
    margin: 0,
    fontWeight: 700,
  },
  navigation: {
    display: 'flex',
    gap: '15px',
  },
  navButton: {
    background: 'none',
    border: '1px solid #007AFF',
    color: '#007AFF',
    padding: '8px 16px',
    borderRadius: '6px',
    cursor: 'pointer',
    fontWeight: 500,
    transition: 'background-color 0.2s ease, color 0.2s ease',
  },
  subtitle: {
    fontSize: '1.2rem',
    color: '#555',
    margin: '0 0 20px 0',
    textAlign: 'center',
  },
  mainContent: {
    maxWidth: '800px',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    flexGrow: 1,
  },
  introText: {
    fontSize: '1.1rem',
    color: '#4A4A4A',
    lineHeight: 1.6,
    marginBottom: '30px',
    textAlign: 'center',
  },
  ctaButton: {
    backgroundColor: '#007AFF',
    color: 'white',
    border: 'none',
    padding: '15px 30px',
    fontSize: '1.1rem',
    fontWeight: 600,
    borderRadius: '8px',
    cursor: 'pointer',
    boxShadow: '0px 4px 15px rgba(0, 122, 255, 0.3)',
    transition: 'background-color 0.3s ease, transform 0.2s ease, box-shadow 0.3s ease',
    marginBottom: '30px',
    marginTop: '10px',
  },
  featuresPreview: {
    display: 'flex',
    justifyContent: 'space-around',
    gap: '20px',
    flexWrap: 'wrap',
    marginBottom: '40px',
    width: '100%',
  },
  featureCard: {
    backgroundColor: '#f9f9f9',
    padding: '20px',
    borderRadius: '10px',
    boxShadow: '0px 5px 15px rgba(0,0,0,0.05)',
    width: 'calc(33% - 20px)',
    minWidth: '250px',
    textAlign: 'left',
    cursor: 'pointer',
  },
  featureTitle: {
    fontSize: '1.3rem',
    color: '#007AFF',
    marginBottom: '10px',
  },
  featureDescription: {
    fontSize: '0.95rem',
    color: '#666',
    lineHeight: 1.5,
  },
  authFormContainer: {
    maxWidth: '450px',
    padding: '30px',
    backgroundColor: '#fdfdfd',
    borderRadius: '10px',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.08)',
  },
  authTitle: {
    fontSize: '1.8rem',
    color: '#333',
    marginBottom: '25px',
    textAlign: 'center',
  },
  authForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    width: '100%',
  },
  label: {
    display: 'block',
    fontSize: '0.9rem',
    color: '#555',
    marginBottom: '5px',
    fontWeight: 500,
    textAlign: 'left',
  },
  inputField: {
    width: '100%',
    padding: '12px 15px',
    fontSize: '1rem',
    border: '1px solid #ddd',
    borderRadius: '6px',
    boxSizing: 'border-box',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
    outline: 'none',
  },
  authLink: {
    textAlign: 'center',
    marginTop: '25px',
    fontSize: '0.95rem',
    color: '#555',
  },
  linkButton: {
    background: 'none',
    border: 'none',
    color: '#007AFF',
    textDecoration: 'underline',
    cursor: 'pointer',
    fontSize: '0.95rem',
    padding: 0,
    fontWeight: 600,
  },
  footer: {
    marginTop: 'auto',
    padding: '20px 0',
    fontSize: '0.9rem',
    color: '#777',
    borderTop: '1px solid #eee',
    width: '100%',
    textAlign: 'center',
  },
  dashboardGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: '20px',
    width: '100%',
    marginTop: '20px',
  },
  dashboardCard: {
    backgroundColor: '#f9f9f9',
    padding: '25px',
    borderRadius: '12px',
    boxShadow: '0px 6px 18px rgba(0,0,0,0.06)',
    textAlign: 'left',
    cursor: 'pointer',
    transition: 'transform 0.2s ease-out, box-shadow 0.2s ease-out',
  },
}; 